<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA6XgBWz\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA6XgBWz/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA6XgBWz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA6XgBWz\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerA6XgBWz\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'A6XgBWz',
    'container.build_id' => 'e39caa02',
    'container.build_time' => 1635813482,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA6XgBWz');
